[
  [
    {
      id: 447351846,
      syllabusCourse: {
        id: 444059155,
        maxMark: 100.0,
        internalMarks: 0.0,
        internalPassMarks: 0.0,
        externalMarks: 0.0,
        externalPassMarks: 0.0,
        passMark: 0.0,
        credit: 4.0,
        durationInHours: 0,
        courseClassType: {
          id: 369459212,
          credits: 0.0,
          course: {
            id: 369426444,
            code: "BIS398",
            name: "Independent Study",
            credit: 0.0,
            contactHours: 0.0,
            otherDirectedHours: 0.0,
            totDirectedHours: 0.0,
            selfDirectedHours: 0.0,
            totLearningHours: 0.0,
            sequenceOrder: 0,
          },
          classType: { code: "IP/IS/UR", name: "IP/IS/UR" },
        },
        courseType: { name: "Department Elective", isMandatory: 0 },
        feedBackOnline: false,
        classHours: 0,
        tutorialHours: 0,
        labHours: 0,
        workHours: 0,
        concentration: 0,
      },
      admission: {
        id: 406224948,
        entranceScore: 0.0,
        entranceRank: 0,
        totalMark: 0.0,
        cgpa: 0.0,
        feeAmount: 0.0,
        rollNo: 0,
        student: {
          id: 406192160,
          pinNo: 0,
          parentAnnualIncome: 0.0,
          age: 0,
          workExperince: 0,
        },
        studentCurrentTerm: 0.0,
      },
      level: {
        id: 443678826,
        syllabusFreeze: false,
        startDate: "Jan 3, 2024 12:00:00 AM",
        endDate: "May 24, 2024 11:59:59 PM",
        resultApplicable: false,
        resultDeclared: false,
        sgpaCgpaCalStatus: 0,
      },
      courseType: 0,
      feedBack: 0,
      forcedGrade: {
        id: 16908289,
        code: "A",
        weightage: 10.0,
        hierarchyId: 0,
        fromPR: 0.0,
        toPR: 0.0,
        fromMR: 0,
        toMR: 0,
      },
      totalMark: 0.0,
      internalMark: 0.0,
      externalMark: 0.0,
      passAudit: false,
      thesis:
        "Exploring the Fundamentals of the Stock Market and Algorithmic Trading: A Comprehensive\u0026nbsp;Study",
      otherStatus: 0,
      modifiedGroup: "campus",
    },
    [],
    true,
  ],
  [
    {
      id: 444702457,
      syllabusCourse: {
        id: 444059160,
        maxMark: 100.0,
        internalMarks: 0.0,
        internalPassMarks: 0.0,
        externalMarks: 0.0,
        externalPassMarks: 0.0,
        passMark: 0.0,
        credit: 4.0,
        durationInHours: 0,
        courseClassType: {
          id: 315195403,
          credits: 0.0,
          course: {
            id: 315162635,
            code: "BTP499",
            name: "BTech Project",
            credit: 0.0,
            contactHours: 0.0,
            otherDirectedHours: 0.0,
            totDirectedHours: 0.0,
            selfDirectedHours: 0.0,
            totLearningHours: 0.0,
            sequenceOrder: 0,
          },
          classType: { code: "Thesis", name: "Thesis" },
        },
        courseType: { name: "Department Elective", isMandatory: 0 },
        feedBackOnline: false,
        classHours: 0,
        tutorialHours: 0,
        labHours: 0,
        workHours: 0,
        concentration: 0,
      },
      admission: {
        id: 406224948,
        entranceScore: 0.0,
        entranceRank: 0,
        totalMark: 0.0,
        cgpa: 0.0,
        feeAmount: 0.0,
        rollNo: 0,
        student: {
          id: 406192160,
          pinNo: 0,
          parentAnnualIncome: 0.0,
          age: 0,
          workExperince: 0,
        },
        studentCurrentTerm: 0.0,
      },
      level: {
        id: 443678826,
        syllabusFreeze: false,
        startDate: "Jan 3, 2024 12:00:00 AM",
        endDate: "May 24, 2024 11:59:59 PM",
        resultApplicable: false,
        resultDeclared: false,
        sgpaCgpaCalStatus: 0,
      },
      courseType: 0,
      feedBack: 0,
      forcedGrade: {
        id: 16908289,
        code: "A",
        weightage: 10.0,
        hierarchyId: 0,
        fromPR: 0.0,
        toPR: 0.0,
        fromMR: 0,
        toMR: 0,
      },
      totalMark: 0.0,
      internalMark: 0.0,
      externalMark: 0.0,
      passAudit: false,
      thesis: "Smart Gym System",
      otherStatus: 0,
      modifiedGroup: "campus",
    },
    [],
    true,
  ],
  [
    {
      id: 444702641,
      syllabusCourse: {
        id: 444059211,
        maxMark: 100.0,
        internalMarks: 0.0,
        internalPassMarks: 0.0,
        externalMarks: 0.0,
        externalPassMarks: 0.0,
        passMark: 0.0,
        credit: 4.0,
        durationInHours: 0,
        courseClassType: {
          id: 109641729,
          credits: 0.0,
          course: {
            id: 109608961,
            code: "CSE350",
            name: "Network Security",
            credit: 0.0,
            contactHours: 0.0,
            otherDirectedHours: 0.0,
            totDirectedHours: 0.0,
            selfDirectedHours: 0.0,
            totLearningHours: 0.0,
            sequenceOrder: 0,
          },
          classType: { code: "Lect", name: "Lecture" },
        },
        courseType: { name: "Department Elective", isMandatory: 0 },
        feedBackOnline: false,
        classHours: 0,
        tutorialHours: 0,
        labHours: 0,
        workHours: 0,
        concentration: 0,
      },
      admission: {
        id: 406224948,
        entranceScore: 0.0,
        entranceRank: 0,
        totalMark: 0.0,
        cgpa: 0.0,
        feeAmount: 0.0,
        rollNo: 0,
        student: {
          id: 406192160,
          pinNo: 0,
          parentAnnualIncome: 0.0,
          age: 0,
          workExperince: 0,
        },
        studentCurrentTerm: 0.0,
      },
      level: {
        id: 443678826,
        syllabusFreeze: false,
        startDate: "Jan 3, 2024 12:00:00 AM",
        endDate: "May 24, 2024 11:59:59 PM",
        resultApplicable: false,
        resultDeclared: false,
        sgpaCgpaCalStatus: 0,
      },
      courseType: 0,
      feedBack: 2,
      forcedGrade: {
        id: 16908291,
        code: "B",
        weightage: 8.0,
        hierarchyId: 0,
        fromPR: 0.0,
        toPR: 0.0,
        fromMR: 0,
        toMR: 0,
      },
      totalMark: 0.0,
      internalMark: 0.0,
      externalMark: 0.0,
      passAudit: false,
      otherStatus: 0,
      modifiedGroup: "campus",
    },
    [],
    false,
  ],
  [
    {
      id: 444700738,
      syllabusCourse: {
        id: 444059256,
        maxMark: 100.0,
        internalMarks: 0.0,
        internalPassMarks: 0.0,
        externalMarks: 0.0,
        externalPassMarks: 0.0,
        passMark: 0.0,
        credit: 4.0,
        durationInHours: 0,
        courseClassType: {
          id: 383123461,
          credits: 0.0,
          course: {
            id: 383090693,
            code: "CSE530",
            name: "Distributed Systems: Concepts \u0026 Design",
            credit: 0.0,
            contactHours: 0.0,
            otherDirectedHours: 0.0,
            totDirectedHours: 0.0,
            selfDirectedHours: 0.0,
            totLearningHours: 0.0,
            sequenceOrder: 0,
          },
          classType: { code: "Lect", name: "Lecture" },
        },
        courseType: { name: "Department Elective", isMandatory: 0 },
        feedBackOnline: false,
        classHours: 0,
        tutorialHours: 0,
        labHours: 0,
        workHours: 0,
        concentration: 0,
      },
      admission: {
        id: 406224948,
        entranceScore: 0.0,
        entranceRank: 0,
        totalMark: 0.0,
        cgpa: 0.0,
        feeAmount: 0.0,
        rollNo: 0,
        student: {
          id: 406192160,
          pinNo: 0,
          parentAnnualIncome: 0.0,
          age: 0,
          workExperince: 0,
        },
        studentCurrentTerm: 0.0,
      },
      level: {
        id: 443678826,
        syllabusFreeze: false,
        startDate: "Jan 3, 2024 12:00:00 AM",
        endDate: "May 24, 2024 11:59:59 PM",
        resultApplicable: false,
        resultDeclared: false,
        sgpaCgpaCalStatus: 0,
      },
      courseType: 0,
      feedBack: 2,
      forcedGrade: {
        id: 16908291,
        code: "B",
        weightage: 8.0,
        hierarchyId: 0,
        fromPR: 0.0,
        toPR: 0.0,
        fromMR: 0,
        toMR: 0,
      },
      totalMark: 0.0,
      internalMark: 0.0,
      externalMark: 0.0,
      passAudit: false,
      otherStatus: 0,
      modifiedGroup: "campus",
    },
    [],
    false,
  ],
  [
    {
      id: 444700739,
      syllabusCourse: {
        id: 444059262,
        maxMark: 100.0,
        internalMarks: 0.0,
        internalPassMarks: 0.0,
        externalMarks: 0.0,
        externalPassMarks: 0.0,
        passMark: 0.0,
        credit: 4.0,
        durationInHours: 0,
        courseClassType: {
          id: 34734080,
          credits: 0.0,
          course: {
            id: 34701312,
            code: "CSE535",
            name: "Mobile Computing",
            credit: 0.0,
            contactHours: 0.0,
            otherDirectedHours: 0.0,
            totDirectedHours: 0.0,
            selfDirectedHours: 0.0,
            totLearningHours: 0.0,
            sequenceOrder: 0,
          },
          classType: { code: "Lect", name: "Lecture" },
        },
        courseType: { name: "Department Elective", isMandatory: 0 },
        feedBackOnline: false,
        classHours: 0,
        tutorialHours: 0,
        labHours: 0,
        workHours: 0,
        concentration: 0,
      },
      admission: {
        id: 406224948,
        entranceScore: 0.0,
        entranceRank: 0,
        totalMark: 0.0,
        cgpa: 0.0,
        feeAmount: 0.0,
        rollNo: 0,
        student: {
          id: 406192160,
          pinNo: 0,
          parentAnnualIncome: 0.0,
          age: 0,
          workExperince: 0,
        },
        studentCurrentTerm: 0.0,
      },
      level: {
        id: 443678826,
        syllabusFreeze: false,
        startDate: "Jan 3, 2024 12:00:00 AM",
        endDate: "May 24, 2024 11:59:59 PM",
        resultApplicable: false,
        resultDeclared: false,
        sgpaCgpaCalStatus: 0,
      },
      courseType: 0,
      feedBack: 2,
      forcedGrade: {
        id: 16908290,
        code: "A-",
        weightage: 9.0,
        hierarchyId: 0,
        fromPR: 0.0,
        toPR: 0.0,
        fromMR: 0,
        toMR: 0,
      },
      totalMark: 0.0,
      internalMark: 0.0,
      externalMark: 0.0,
      passAudit: false,
      otherStatus: 0,
      modifiedGroup: "campus",
    },
    [],
    false,
  ],
];
